# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sb_SPin_Wcbf-VpmuOqTQM6EKMS2WohI
"""

lista =  [1,[2,3],4,[5,6,[7,8],9],10,11,12]


for i in range(len(lista)):
  print(lista[i])


def flatten(iterable):
    lst = []
    for i in iterable:
        if isinstance(i, (list, tuple)):
            lst.extend(flatten(i)) # was lst += flatten(e) :)
        else:
            lst.append(i)
    return lst

flatten(lista)

# prueba


def aplanar(lst: list[list]) -> list): 
  #retorna lista y recibe lista d elistas
  plana = []

  for l in lst:
    for x in l: 
      # itera ren la pequena lista
      plana.append(x)
  return plana

lista =  [1,[2,3],4,[5,6,[7,8],9],10,11,12]
aplanar(lista)

# prueba
lista =  [1,[2,3],4,[5,6,[7,8],9],10,11,12]

def aplanar(lst): 
  #retorna lista y recibe lista d elistas
  plana = []

  for l in lst:
    plana.extend(l)
  return plana

aplanar(lista)