# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sb_SPin_Wcbf-VpmuOqTQM6EKMS2WohI
"""

# diagonal displaced matrix
filas = 3 ; columnas = 3 ; mat = []  
for i in range(filas):
  mat.append([])  
  for j in range(columnas):
    mat[i].append(0)

counter = 1
for i  in range(len(mat)):
  counter += 1
  # print(counter)  2 3 4
  for j in range(len(mat[0])):
    if i == j :
      mat[i][j] = 1
   
  if i != j :
    mat[i][j] = counter
    mat[j][i] = counter
  
#funciona en 3x3 pq ?
    


print(mat)
for i in range(len(mat)):
  print(mat[i])

#___hacer el contador inside the loop
#create the matrix 
filas = 4 ; columnas = 10 ; mat = []  
for i in range(filas):
  mat.append([])  
  for j in range(columnas):
    mat[i].append(0)

counter = 0
shift = 5

for i  in range(len(mat)):
  counter += 1
  #print(counter)
  for j in range(columnas):
    #print("--")
    if i == j and  (j + shift) < columnas  :
      mat[i][j + shift] = counter


for i in range(len(mat)):
  print(mat[i])

#___hacer el contador inside the loop
#create the matrix 
filas = 20 ; columnas = 20 ; mat = []  
for i in range(filas):
  mat.append([])  
  for j in range(columnas):
    mat[i].append(0)

counter = 0
shift = 1

for i  in range(len(mat)):
  counter += 1
  #print(counter)
  for j in range(columnas):
    #print("--")
    if i == j and  (j + shift) < columnas  :
      mat[i][j + shift] = counter
      #mat[i][j] = 1
    if j > 0 and i == j :
      mat[i][j - shift] = -(counter-1)
      
    


for i in range(len(mat)):
  print(mat[i]) 

  # cuando vario el shift corre para mabos lados