# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sb_SPin_Wcbf-VpmuOqTQM6EKMS2WohI
"""

# Tic Tac toe de matrices = WTF
i = 0
a = True

turno = 0  # empiezan los circulos
filas = 3 ; columnas = 3 ; tablero = []  #creando el tablero
for i in range(filas):
  tablero .append([])  # crea este patron [[], [], []]
  for j in range(columnas):
    # print(i)  0 0 0   1 1 1  2 2 2
    tablero[i].append('-')
    #print(tablero)


def ingresarCoordenada():
  coordenada = []
  
  i, j = [int(x) for x in input("ingrese coordenada:").split()] 
  #i, j = input(),  input()
  coordenada.append([i,j])
  # print(coordenada)

  return i , j

def asignarCoorToTablero(i,j,turno):
  if turno == 0 :
    simbolo = 'O'
  elif turno == 1:
    simbolo = 'X'
  tablero[i][j] = simbolo

  print(tablero)



while a == True:
  
  flagTurno = i % 2  # produce sequencias de 0 1
  turno = flagTurno

  

  if turno ==  0:
    
    i,j = ingresarCoordenada()
    asignarCoorToTablero(i,j,turno)
  elif turno == 1 :
    
    i,j = ingresarCoordenada()
    asignarCoorToTablero(i,j,turno)

  
  i += 1


  if i == 14:
    a = False

