# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sb_SPin_Wcbf-VpmuOqTQM6EKMS2WohI
"""

filas = 3 ; columnas = 3 ; mat = []  
for i in range(filas):
  mat.append([])  
  for j in range(columnas):
    mat[i].append(0)

  
for i  in range(len(mat)):
  for j in range(len(mat[0])):
    if i == j :
      mat[i][j] = 1
      
print(mat)
for i in range(len(mat)):
  print(mat[i])

filas = 5 ; columnas = 5 ; mat = []  
for i in range(filas):
  mat.append([])  
  for j in range(columnas):
    mat[i].append(0)

counter = 1
for i  in range(len(mat)):
  counter += 1
  # print(counter)  2 3 4
  for j in range(len(mat[0])):
    if i == j :
      mat[i][j] = 1
   
  if i != j :
    mat[i][j] = counter
    mat[j][i] = counter
  
#funciona en 3x3 pq ?
    


print(mat)
for i in range(len(mat)):
  print(mat[i])

filas = 3 ; columnas = 3 ; mat = []  
for i in range(filas):
  mat.append([])  
  for j in range(columnas):
    mat[i].append(0)

counter = 1
for i  in range(len(mat)):
  counter += 1
  # print(counter)  2 3 4
  for j in range(len(mat[0])):
    if i == j :
      mat[i][j] = 1
   
  if i != j :
    mat[i][j] = counter
    mat[j][i] = counter
  
#funciona en 3x3 pq ?
    


print(mat)
for i in range(len(mat)):
  print(mat[i])