# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12MZYaW_vraBVmD6EwUJHdrmTrJR5hutx
"""

# matrix ideas
filas = 4 ; columnas = 4

dimension = filas * columnas

element = 1

matriz = []
for j in range(0,filas):
  matriz.append([0] * columnas)

for i in range(filas):
  for j in range(columnas):
    matriz[i][j] = element
    element += 1 

print(matriz)

filas = 4 ; columnas = 4

dimension = filas * columnas

element = 1

matriz = []
for j in range(0,filas):
  matriz.append([0] * columnas)

for j in range(columnas):
  for i in range(filas):
    matriz[i][j] = element
    element += 1 
   

print(matriz)

import numpy as np

oneD = np.array([1,2,3,4,5] )

oneD = np.reshape( oneD, (len(oneD),1))

def sumarUnidad(x):
  return x + 1


matriz = [[1],
          [2],
          [3],
          [4],
          [5]];

filas = len(oneD) #Height
columnas = len(oneD[0]) #Width
print(columnas)

columnas += 1
#anadir una columna mas 
for j in range(0,filas):
  matriz.append([j] * columnas)

print(matriz)

