# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kwWXoEMXll4diLyE3U7YOkOAHBpJFSHZ
"""

# patrones

filas = 10
col = 10
mat = []
def print_matriz():
  for i in mat:
    print(i)
  print("__________________________")

for i in range(0,filas):
  mat.append([0] * col)


print_matriz()



for i in range(0,filas):
   for j in range(col):
    #print(j,i) # column
    #mat[i].append(j)
    mat[j][j] = j

print_matriz()

#______________________________##
filas = 11
col = 11
mat = []
for i in range(0,filas):
  mat.append([0] * col)

def print_matriz():
  for i in mat:
    print(i)
  print("__________________________")

for i in range(0,filas):
   for j in range(0,col):
     #print(j%2)
     if (j % 2) == 0 :
       mat[i][j] = 0      
     elif (j % 2)!= 0:
       mat[i][j] = 1
     
  
print_matriz()

#____________________________#
for i in range(0,filas):
   for j in range(0,col):
     #print(j%2)
     if (j % 2) == 0 :
       mat[i][j] = i     
     elif (j % 2) != 0 :
       mat[i][j] = 1
     
  
print_matriz()

#____________________________#
if (col % 2 ) != 0:
  for i in range(0,filas):
    if i % 2 == 0 :
      primero = 0
      segundo = 1
    else:
      primero = 1
      segundo = 0
    for j in range(0,col):
      if (j % 2) == 0 :
       mat[i][j] = primero     
      elif (j % 2) != 0 :
       mat[i][j] = segundo
        
print_matriz()
#____________________________#
for i in range(0,filas):
   for j in range(0,col):
     #print(j%2)
     if (i + j) % 2 == 0 :
       mat[i][j] = 0      
     elif (i + j) % 2 != 0:
       mat[i][j] = 1
     
  
print_matriz()

filas = 10
col = 0
mat = []
def print_matriz():
  for i in mat:
    print(i)
  print("__________________________")

for i in range(0,filas):
  mat.append([col] * col)
  col += 1

print_matriz()

#_______________________________________

for i in range(0,filas):
  for j in range(0, filas - i):
    mat.append([0])



print_matriz()