# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/113QtH4VHLepJCe3bJbAoqR-_itxST4nW
"""

# matrices d epermutacion

a = [[0,1],[1,0]]
b = [[1,2],[3,4]]

#tomar las dimensiones para la nueva matriz a ser creada 
aRows = len(a) ; aCol = len(a[0])
bRows = len(b) ; bCol = len(b[0])
# new dim

if aCol == bRows :
   fila = aRows ; col = bCol
c = []
for j in range(0,fila):
  c.append([0]*col)


# a la izquierda a *b  => cambia las filas las permuta

for i in range(len(a)): # iterar sobre las filas de x
  for j in range(len(b[0])):
    #print(i,j)
    for k in range(len(b)): # iterar sobre las filas de b 
      #print(i,j,k)
      c[i][j] += a[i][k] * b[k][j] 

print(b,c)

# a la derecha => intercambia la columna

# en una matriz 3x3 => {123} {132} , {213}{231} , {312} {321}  = factorial(3)
# Find the inverses of all the three-by-three permutation matrices.  Explain why some matrices are their own inverses, and others are not.