# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TQKnF58vyRdOYaa_j78azEZZQw3MMTzn
"""

# tabla de cayley
g = [0,1] #elementos

tamano = len(g)

cayley = []
for i in range(len(g)):
  for j in range(len(g)):
    print(i,j)

# https://www.codegrepper.com/code-examples/python/how+to+traverse+2d+array+in+python

